### ISSUE TITLE
Update pre-commit markdown formatter 

### ISSUE THREAD

**Issue by dcmiddle** [opea-project/GenAIComps#765]
Our pre-commit hook [1] uses an archived [2] adaptation of prettier [3].

Relying on archived or otherwise unmaintained code creates risks.
The ideal replacement will automatically fix common formatting errors so that we don't need to handle those during code reviews.
It should also integrate with the existing pre-commit strategy, i.e., it should be added as part of that same pre-commit-config.yaml file.

[1] https://github.com/opea-project/GenAIComps/blob/3ac391a1d2a0e62d335a99865c7aa88f113cbca9/.pre-commit-config.yaml#L89
[2] https://github.com/pre-commit/mirrors-prettier/blob/f62a70a3a7114896b062de517d72829ea1c884b6/README.md#archived
[3] https://github.com/prettier/prettier

**Comment by chickenrae** [comment]
Done :)

**Comment by Khangf** [comment]
@chickenrae
Thanks for assigning.
Quick check here, looking at the current pre-commit workflow, we are now using prettier to perform formatting for multiple supported file types from prettier.
Since prettier no longer supported from pre-commit, are we looking for a different formatter to perform the multiple file formatting or this issue only focus on the markdown files?

**Comment by Khangf** [comment]
I've found a way to continue leverage Prettier but as a node package that run locally in the repo. Do you think this is good enough to solve this?
https://github.com/Khangf/GenAIComps/commit/647b58b511fa5818b3b218f131f2f88ab76b488f

**Comment by dcmiddle** [comment]
Sounds good to me! That makes much more sense than finding different tools.
